[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
watchPatterns = [
  "/backend/**",
  "/backend/data/**",
  "/frontend/public/**",
  "/backend/prisma/**",
  "/railway.toml",
  "/package.json"
]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm --prefix backend start"
