export const SOURCE_RELEVANCE_RULES = [
  {
    name: "Veridos Press & Media",
    sourceKeys: ["veridos press & media", "veridos.com/en/about/press-media"],
    rejectPagePatterns: [
      "/home.html",
      "/career",
      "/careers",
      "/downloads",
      "/imprint",
      "/projects",
      "/support",
    ],
    rejectExactPaths: [
      "/en",
      "/home",
      "/en/home",
      "/en/home.html",
      "/en/about/press-media",
      "/en/about/press-media/press-releases",
    ],
    rejectTitlePatterns: [
      "careers",
      "downloads",
      "home",
      "imprint",
      "projects",
      "support",
    ],
    include: [
      "credential",
      "credentials",
      "eid",
      "government identity",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "secure identities",
      "secure identity",
      "travel document",
      "travel documents",
    ],
    exclude: [
      "career",
      "careers",
      "download",
      "downloads",
      "imprint",
      "job",
      "jobs",
      "project overview",
      "support",
    ],
  },
  {
    name: "IN Groupe Newsroom",
    sourceKeys: ["in groupe newsroom", "ingroupe.com/newsroom"],
    rejectPagePatterns: [
      "/a-global-company",
      "/about",
      "/brands",
      "/company",
      "/customer-case",
      "/customer-cases",
      "/customers",
      "/dsar",
      "/group",
      "/integrity-and-compliance",
      "/innovation",
      "/leadership",
      "/media-library",
      "/mediatheque",
      "/newsroom/media",
      "/purpose",
      "/responsibility",
      "/strategy",
      "/values",
      "/values-purpose",
      "/vision-and-strategy",
      "/you-are-government",
      "/you-are-business",
    ],
    rejectExactPaths: [
      "/newsroom",
      "/en/newsroom",
      "/fr/newsroom",
    ],
    rejectTitlePatterns: [
      "corporate responsibility",
      "customer case",
      "customer cases",
      "data subject access request",
      "media library",
      "new organization and executive committee",
      "the group brands",
      "newsroom",
      "welcome to our media library",
      "welcome to our newsroom",
      "we help governments assert their sovereignty",
    ],
    include: [
      "credential",
      "credentials",
      "banknote",
      "banknotes",
      "digital identity",
      "eid",
      "government identity",
      "identities",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "secure identity",
      "secure identities",
      "security thread",
    ],
    exclude: [
      "compliance",
      "corporate responsibility",
      "customer case",
      "customer cases",
      "media library",
      "values and purpose",
      "vision and strategy",
    ],
  },
  {
    name: "HID Press Releases",
    sourceKeys: ["hid press releases", "newsroom.hidglobal.com/press-releases"],
    rejectPagePatterns: [
      "/es/press-releases",
      "/pt/press-releases",
      "/de/press-releases",
      "/fr/press-releases",
    ],
    rejectExactPaths: [
      "/press-releases",
      "/en/press-releases",
      "/es/press-releases",
      "/pt/press-releases",
      "/de/press-releases",
      "/fr/press-releases",
    ],
    rejectTitlePatterns: [
      "press releases",
    ],
    include: [
      "credential",
      "credentials",
      "document",
      "documents",
      "eid",
      "government id",
      "government identity",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure identity",
      "secure identities",
    ],
    exclude: [
      "commercial launch",
      "embedded application environment",
      "mercury security",
      "press release index",
      "school safety",
    ],
  },
  {
    name: "SICPA Newsroom",
    sourceKeys: ["sicpa newsroom", "sicpa.com/all-press-releases"],
    include: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "digital identity",
      "digital identity wallet",
      "digital passport",
      "digital travel credential",
      "eid",
      "excise stamp",
      "identity document",
      "id document",
      "passport",
      "passports",
      "secure document",
      "security printing",
      "sovereign solutions",
      "tax stamp",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "digital identity wallet",
      "digital passport",
      "digital travel credential",
      "eid",
      "excise stamp",
      "identity document",
      "id document",
      "passport",
      "passports",
      "secure document",
      "security printing",
      "tax stamp",
    ],
    exclude: [
      "campus",
      "community",
      "corporate social responsibility",
      "csr",
      "education",
      "erp",
      "fuel integrity",
      "fuel marking",
      "minergie",
      "sap",
      "sustainability report",
      "underserved communities",
      "water scarcity",
    ],
  },
  {
    name: "G+D Press Releases",
    sourceKeys: ["g+d press releases", "gi-de.com/en/about-us/press/press-releases"],
    rejectPagePatterns: [
      "/about-us/ventures",
      "/currency-technology/currency-management",
      "/currency-technology/software",
      "/currency-technology/cash",
      "/identity-technologies/veridos",
      "/ventures",
      "/veridos",
    ],
    rejectExactPaths: [
      "/en",
      "/en/about-us/press/press-releases",
    ],
    rejectTitlePatterns: [
      "end-to-end cash and currency management",
      "g+d ventures",
      "secure cash management software",
      "veridos - your trusted identity partner",
    ],
    include: [
      "authentication",
      "banknote",
      "banknotes",
      "cash",
      "credential",
      "credentials",
      "currency",
      "government identity",
      "identity",
      "identity documents",
      "identity technology",
      "passport",
      "passports",
      "public sector identity",
      "secure document",
      "secure documents",
      "secure identities",
      "secure identity",
      "security printing",
      "sovereign solutions",
      "veridos",
      "xtec",
    ],
    exclude: [
      "5g",
      "asset tracking",
      "banking market",
      "cloud-based remote esim",
      "compliance expert",
      "connected car",
      "connectivity",
      "crypto",
      "digital payments",
      "esim",
      "e-sim",
      "iot",
      "mobile ticketing",
      "netcetera",
      "payment security",
      "payment",
      "payments",
      "rabo investments",
      "remote esim",
      "rivian",
      "secunet",
      "sim",
      "telecom",
      "telecommunications",
      "trusted software",
      "wearable",
    ],
  },
  {
    name: "Crane Currency News & Insights",
    sourceKeys: ["crane currency news & insights", "cranecurrency.com/news-insights"],
    rejectPagePatterns: [
      "/media/",
      "/solutions/",
    ],
    rejectExactPaths: [
      "/news-insights",
    ],
    rejectTitlePatterns: [
      "news & insights",
    ],
    include: [
      "anti-counterfeit",
      "banknote",
      "banknotes",
      "banknote design",
      "cash",
      "cash cycle",
      "central bank",
      "counterfeit",
      "currency manager",
      "detect",
      "issuing authority",
      "micro optic",
      "micro-optic",
      "micro optics",
      "motion",
      "motion surface",
      "polymer",
      "rapid",
      "security feature",
      "security features",
      "security thread",
      "substrate",
    ],
    protectedPagePatterns: [
      "/news-insights/",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "banknote",
      "banknotes",
      "banknote design",
      "cash",
      "cash cycle",
      "central bank",
      "counterfeit",
      "currency manager",
      "issuing authority",
      "micro optic",
      "micro-optic",
      "micro optics",
      "motion surface",
      "polymer",
      "rapid",
      "security feature",
      "security features",
      "security thread",
    ],
    exclude: [
      "anniversary",
      "community",
      "donation",
      "facility",
      "generic company news",
      "solar farm",
      "sustainability",
    ],
  },
  {
    name: "KURZ Press Releases",
    sourceKeys: ["kurz press releases", "kurz-world.com/en/newsroom/press"],
    include: [
      "anti-counterfeit",
      "anticounterfeit",
      "banknote",
      "banknotes",
      "card",
      "cards",
      "counterfeit",
      "counterfeits",
      "currency",
      "forgeries",
      "forgery",
      "high security",
      "hologram",
      "holograms",
      "holography",
      "identity",
      "ovd",
      "optical security",
      "secure document",
      "secure documents",
      "security feature",
      "security features",
      "security printing",
      "trustseal",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "anticounterfeit",
      "banknote",
      "banknotes",
      "counterfeit protection",
      "counterfeit",
      "counterfeits",
      "forgeries",
      "forgery",
      "hologram",
      "holograms",
      "holography",
      "ovd",
      "security against counterfeits",
      "security feature",
      "security features",
      "security printing",
    ],
    exclude: [
      "automotive",
      "beverage",
      "brand enhancement",
      "consumer electronics",
      "cosmetics",
      "decoration",
      "decorative",
      "decorative finishing",
      "embellishment",
      "home appliances",
      "jersey",
      "labels",
      "luxe pack",
      "mobility",
      "packaging",
      "pentawards",
      "rpet",
      "spirits",
      "surface finishing",
      "textile",
      "textiles",
      "vestel",
      "wine",
      "wine & spirits",
    ],
  },
  {
    name: "OVD Kinegram Insights",
    sourceKeys: ["ovd kinegram insights", "kinegram.com/events-insights/insights"],
    rejectExactPaths: [
      "/events-insights/insights",
    ],
    rejectTitlePatterns: [
      "news and insights by ovd kinegram",
    ],
    include: [
      "card",
      "cards",
      "credential",
      "document security",
      "government document",
      "government documents",
      "hologram",
      "holography",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "kinegram",
      "ovd",
      "passport",
      "passports",
      "polycarbonate",
      "secure document",
      "secure documents",
      "security feature",
      "security features",
      "travel document",
      "travel documents",
    ],
    protectedPagePatterns: [
      "/events-insights/insights/",
    ],
    protectedInclude: [
      "document security",
      "government documents",
      "hologram",
      "identity document",
      "identity documents",
      "id card",
      "kinegram",
      "ovd",
      "passport",
      "passports",
      "polycarbonate",
      "security feature",
      "security features",
    ],
    exclude: [
      "career",
      "careers",
      "event registration",
      "job",
      "jobs",
      "newsletter",
    ],
  },
  {
    name: "Louisenthal Press Releases",
    sourceKeys: ["louisenthal press releases", "louisenthal.com/highlights/news/press-releases"],
    rejectExactPaths: [
      "/highlights/news/press-releases",
    ],
    rejectTitlePatterns: [
      "press releases",
    ],
    include: [
      "banknote",
      "banknotes",
      "currency",
      "holography",
      "iaca",
      "security feature",
      "security features",
      "security foil",
      "security thread",
      "substrate",
      "varifeye",
    ],
    protectedPagePatterns: [
      "/highlights/news/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "holography",
      "security feature",
      "security features",
      "security foil",
      "security thread",
      "substrate",
    ],
    exclude: [
      "automotive",
      "car heating",
      "interior heating",
      "newsletter",
    ],
  },
  {
    name: "Koenig & Bauer Newsroom",
    sourceKeys: ["koenig & bauer newsroom", "koenig-bauer.com/en/newsroom"],
    rejectExactPaths: [
      "/en/newsroom",
    ],
    rejectTitlePatterns: [
      "koenig & bauer newsroom",
      "newsletter subscription",
      "press contacts",
    ],
    include: [
      "authentication",
      "banknote",
      "banknotes",
      "banknote solutions",
      "currency",
      "currency production",
      "security printing",
      "security print",
      "security printer",
      "valicash",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "banknote solutions",
      "currency production",
      "security printing",
      "valicash",
    ],
    exclude: [
      "annual report",
      "commercial printing",
      "corrugated",
      "packaging",
      "sheetfed",
      "sports",
    ],
  },
  {
    name: "IDEMIA Pressroom",
    sourceKeys: ["idemia pressroom", "idemia.com/pressroom"],
    rejectExactPaths: [
      "/pressroom",
    ],
    rejectTitlePatterns: [
      "pressroom",
      "spokespersons",
    ],
    include: [
      "biometric",
      "biometrics",
      "civil identity",
      "credential",
      "credentials",
      "digital identity",
      "driver license",
      "driver licenses",
      "driving licence",
      "identity",
      "identity verification",
      "id card",
      "id cards",
      "mobile id",
      "passport",
      "passports",
      "public security",
      "secure identity",
      "secure transactions",
      "tsa precheck",
      "wallet",
    ],
    protectedInclude: [
      "biometric",
      "civil identity",
      "digital identity",
      "driver license",
      "driver licenses",
      "identity verification",
      "mobile id",
      "public security",
      "tsa precheck",
    ],
    exclude: [
      "fan experience",
      "iot",
      "la metro",
      "music cards",
      "nickel music",
      "payment card",
      "payment cards",
      "payments",
      "secure transactions powers",
      "sim",
      "tokenization",
    ],
  },
  {
    name: "Thales Digital Identity Newsroom",
    sourceKeys: ["thales digital identity newsroom", "cpl.thalesgroup.com/about-us/newsroom"],
    rejectExactPaths: [
      "/about-us/newsroom",
    ],
    rejectTitlePatterns: [
      "search news release",
      "newsroom",
    ],
    include: [
      "access management",
      "authentication",
      "credential",
      "credentials",
      "digital identity",
      "document verification",
      "identity",
      "identity platform",
      "identity verification",
      "onboarding",
      "onewelcome",
      "passwordless",
      "public sector",
    ],
    protectedInclude: [
      "digital identity",
      "identity platform",
      "identity verification",
      "onewelcome",
      "public sector",
    ],
    exclude: [
      "ai adoption",
      "ai insider threat",
      "bad bot",
      "cybersecurity",
      "data threat",
      "enterprise ai",
      "google cloud",
      "imperva",
      "iot",
    ],
  },
  {
    name: "PWPW RSS",
    sourceKeys: ["pwpw rss", "pwpw.pl/en/rss"],
    include: [
      "banknote",
      "banknotes",
      "card",
      "cards",
      "document",
      "documents",
      "eid",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "security printing",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "identity card",
      "identity document",
      "id card",
      "passport",
      "secure document",
      "security printing",
    ],
    exclude: [
      "anniversary",
      "career",
      "careers",
      "historical tribute",
      "insurgent",
      "insurgents",
      "job",
      "jobs",
      "procurement",
      "tribute paid",
      "tender unrelated",
    ],
  },
  {
    name: "Atlantic Zeiser News",
    sourceKeys: ["atlantic zeiser news", "atlanticzeiser.com/en/news"],
    rejectExactPaths: [
      "/en/news",
    ],
    rejectTitlePatterns: [
      "atlantic zeiser news",
      "latest news",
    ],
    include: [
      "banknote",
      "banknotes",
      "card personalization",
      "currency",
      "document",
      "documents",
      "identity document",
      "id card",
      "passport",
      "secure document",
      "security printing",
      "track and trace",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "card personalization",
      "identity document",
      "security printing",
      "track and trace",
    ],
    exclude: [
      "coding and marking",
      "cosmetics",
      "industrial printing",
      "packaging",
      "pharma packaging",
      "serialization only",
    ],
  },
  {
    name: "Mühlbauer Press",
    sourceKeys: ["mühlbauer press", "muehlbauer press", "muehlbauer.de/company/company/press"],
    rejectExactPaths: [
      "/company/company/press",
    ],
    rejectTitlePatterns: [
      "mühlbauer press",
      "press releases",
    ],
    include: [
      "biometric",
      "biometrics",
      "document verification",
      "eid",
      "government solution",
      "government solutions",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
    ],
    protectedInclude: [
      "biometric",
      "document verification",
      "government solution",
      "identity document",
      "id card",
      "passport",
      "secure document",
    ],
    exclude: [
      "battery",
      "display",
      "emobility",
      "semiconductor",
      "smart factory",
      "solar",
    ],
  },
  {
    name: "MaskTech Press",
    sourceKeys: ["masktech press", "masktech.com/press/60/en"],
    rejectExactPaths: [
      "/press/60/en",
    ],
    include: [
      "eid",
      "electronic identity",
      "government id",
      "government identity",
      "identity",
      "identity card",
      "identity document",
      "id card",
      "national id",
      "secure chip",
      "secure identity",
      "smart card",
    ],
    protectedInclude: [
      "eid",
      "electronic identity",
      "government id",
      "identity card",
      "identity document",
      "national id",
      "secure identity",
      "smart card",
    ],
    exclude: [
      "career",
      "careers",
      "job",
      "jobs",
    ],
  },
  {
    name: "Daon Resources",
    sourceKeys: ["daon resources", "daon.com/resources"],
    rejectExactPaths: [
      "/resources",
    ],
    include: [
      "authentication",
      "biometric",
      "biometrics",
      "digital identity",
      "document verification",
      "identity proofing",
      "identity verification",
      "kyc",
      "liveness",
      "onboarding",
      "passwordless",
      "verification",
    ],
    protectedInclude: [
      "biometric",
      "digital identity",
      "document verification",
      "identity proofing",
      "identity verification",
      "kyc",
      "liveness",
      "onboarding",
    ],
    exclude: [
      "webinar replay only",
      "workforce only",
    ],
  },
  {
    name: "GenKey News",
    sourceKeys: ["genkey news", "genkey.com/news"],
    rejectExactPaths: [
      "/news",
    ],
    include: [
      "biometric",
      "biometrics",
      "civil registry",
      "enrollment",
      "enrolment",
      "government identity",
      "identity",
      "identity management",
      "national id",
      "voter",
      "voter registration",
    ],
    protectedInclude: [
      "biometric",
      "biometrics",
      "civil registry",
      "government identity",
      "identity management",
      "national id",
      "voter registration",
    ],
    exclude: [
      "career",
      "careers",
      "job",
      "jobs",
    ],
  },
  {
    name: "Bundesdruckerei Press Releases",
    sourceKeys: ["bundesdruckerei press releases", "bundesdruckerei.de/en/newsroom/press-releases"],
    rejectPagePatterns: [
      "/antragsportal",
      "/d-trust/portal",
      "/ehealth-antragsportal",
      "/fields-of-use",
      "/fields-use",
      "/group",
      "/portal",
      "/solutions",
      "/trust-services",
    ],
    rejectExactPaths: [
      "/de",
      "/en/newsroom",
      "/en/newsroom/latest-news",
      "/en/newsroom/press-releases",
    ],
    rejectTitlePatterns: [
      "d-trust ehealth antragsportal",
      "d-trust portal",
      "latest news",
      "press releases of the bundesdruckerei-group",
    ],
    include: [
      "ausweis",
      "banknote",
      "banknotes",
      "d-trust",
      "eid",
      "government identity",
      "government solutions",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure identities",
      "secure identity",
      "security printing",
      "self-sovereign identity",
      "trust service",
      "trust services",
    ],
    protectedPagePatterns: [
      "/newsroom/press-releases/",
      "/newsroom/pressemitteilungen/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "banknote of the future",
      "concept banknote",
      "eid",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "quantum computers",
      "secure identity document",
      "secure identity documents",
      "security printing",
    ],
    exclude: [
      "accessibility",
      "accessibility statement",
      "adva network",
      "company restructures",
      "company structure",
      "cooperates with start-ups",
      "corporate",
      "corporate governance",
      "event",
      "events",
      "genua",
      "group structure",
      "innovation hub",
      "industrial remote maintenance",
      "management board",
      "remote maintenance",
      "secunet",
      "start-ups",
      "supervisory board",
      "telematics infrastructure",
      "whistleblowing",
    ],
  },
  {
    name: "ICAO Newsroom",
    sourceKeys: ["icao newsroom", "icao.int/news"],
    rejectExactPaths: [
      "/news",
    ],
    rejectTitlePatterns: [
      "icao newsroom",
    ],
    include: [
      "border interoperability",
      "digital travel credential",
      "doc 9303",
      "emrtd",
      "icao pkd",
      "identity",
      "machine readable",
      "mrtd",
      "mrz",
      "passport",
      "passports",
      "pkd",
      "travel credential",
      "travel document",
      "travel documents",
      "traveller identification programme",
    ],
    protectedPagePatterns: [
      "/news/",
    ],
    protectedInclude: [
      "digital travel credential",
      "doc 9303",
      "icao",
      "passport",
      "pkd",
      "travel document",
    ],
    exclude: [
      "assembly",
      "aviation safety",
      "climate",
      "runway",
      "security council",
    ],
  },
  {
    name: "CBP Newsroom",
    sourceKeys: ["cbp newsroom", "cbp.gov/newsroom", "cbp.gov/newsroom/media-releases/all"],
    rejectPagePatterns: [
      "/250",
      "/travel/",
      "/trusted-traveler-programs/",
    ],
    rejectExactPaths: [
      "/newsroom",
      "/newsroom/media-releases",
      "/newsroom/media-releases/all",
      "/newsroom/accountability-and-transparency",
      "/newsroom/announcements",
      "/newsroom/cbp-live",
      "/newsroom/communicados-de-prensa",
      "/newsroom/documents-library",
      "/newsroom/frontline-digital-magazine",
      "/newsroom/legal-notices",
      "/newsroom/media-releases/all/",
      "/newsroom/multimedia-libraries",
      "/newsroom/publications-catalog",
      "/newsroom/social-media-directory",
      "/newsroom/stats-and-summaries",
    ],
    rejectTitlePatterns: [
      "media releases",
      "newsroom",
    ],
    include: [
      "biometric",
      "biometrics",
      "border",
      "crossing",
      "entry",
      "entry exit",
      "facial recognition",
      "global entry",
      "inspection",
      "mobile passport control",
      "passport",
      "passports",
      "travel document",
      "travel documents",
      "traveler",
      "travellers",
      "trusted traveler",
      "trusted travellers",
      "visa",
      "visas",
    ],
    protectedPagePatterns: [
      "/newsroom/announcements/",
      "/newsroom/local-media-release/",
      "/newsroom/media-release/",
      "/newsroom/media-releases/",
      "/newsroom/national-media-release/",
    ],
    protectedInclude: [
      "biometric",
      "border",
      "facial recognition",
      "mobile passport control",
      "passport",
      "trusted traveler",
      "visa",
    ],
    exclude: [
      "cash seizure",
      "counterfeit merchandise",
      "cocaine",
      "fentanyl",
      "firearms",
      "marijuana",
      "methamphetamine",
      "narcotics",
      "seized",
      "seizure",
    ],
  },
  {
    name: "GOV.UK News and Communications",
    sourceKeys: [
      "gov.uk news and communications",
      "gov.uk/search/news-and-communications",
      "ukvi biometric residence permits",
      "gov.uk/biometric-residence-permits",
      "ukvi brp and brc guidance",
      "gov.uk/government/publications/biometric-residence-permits-guidance",
    ],
    rejectExactPaths: [
      "/biometric-residence-permits",
      "/government/publications/biometric-residence-permits-guidance",
      "/search/news-and-communications",
    ],
    rejectTitlePatterns: [
      "biometric residence permits",
      "biometric residence permits guidance",
      "news and communications",
    ],
    include: [
      "biometric residence permit",
      "biometric residence permits",
      "biometric residence card",
      "biometric residence cards",
      "border",
      "digital immigration status",
      "evisa",
      "home office",
      "identity document",
      "immigration",
      "passport",
      "passports",
      "residence permit",
      "residence permits",
      "travel document",
      "travel documents",
      "ukvi",
      "visa",
      "visas",
    ],
    protectedPagePatterns: [
      "/government/collections/",
      "/government/news/",
      "/government/publications/",
      "/government/speeches/",
    ],
    protectedInclude: [
      "biometric residence permit",
      "evisa",
      "immigration",
      "passport",
      "residence permit",
      "travel document",
      "ukvi",
      "visa",
    ],
    exclude: [
      "farming",
      "flood",
      "hospital",
      "nhs",
      "school",
      "tax",
      "transport",
    ],
  },
  {
    name: "Landqart News",
    sourceKeys: ["landqart news", "landqart.com/en/stories/news"],
    rejectExactPaths: [
      "/en/stories/news",
    ],
    rejectTitlePatterns: [
      "news",
    ],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "central bank",
      "currency",
      "passport",
      "passports",
      "security paper",
      "security substrate",
      "substrate",
      "thread",
      "threads",
      "watermark",
    ],
    protectedPagePatterns: [
      "/en/stories/news/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "central bank",
      "currency",
      "passport",
      "security paper",
      "substrate",
      "watermark",
    ],
    exclude: [
      "award",
      "anniversary",
      "career",
      "careers",
      "csr",
      "graduate",
      "job",
      "jobs",
      "sustainability",
    ],
  },
  {
    name: "POLYVANTIS Press",
    sourceKeys: ["polyvantis press", "polyvantis.com/en/press"],
    rejectExactPaths: [
      "/en/press",
    ],
    rejectTitlePatterns: [
      "press",
    ],
    include: [
      "border control",
      "credential",
      "credentials",
      "eid",
      "government identity",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "passports",
      "polycarbonate",
      "secure document",
      "secure documents",
      "security feature",
      "traffic control",
      "travel document",
    ],
    protectedPagePatterns: [
      "/en/press/",
    ],
    protectedInclude: [
      "credential",
      "eid",
      "identity document",
      "identity documents",
      "polycarbonate",
      "secure document",
      "security feature",
      "travel document",
    ],
    exclude: [
      "aquarium",
      "automotive",
      "construction",
      "furniture",
      "interior",
      "retail display",
      "store fixture",
    ],
  },
  {
    name: "Linxens News & Events",
    sourceKeys: ["linxens news & events", "linxens.com/en/news-events"],
    rejectExactPaths: [
      "/en/news-events",
    ],
    rejectTitlePatterns: [
      "news & events",
    ],
    include: [
      "authentication",
      "biometric",
      "biometrics",
      "credential",
      "credentials",
      "eid",
      "embedded security",
      "government identity",
      "identity",
      "identity documents",
      "inlay",
      "inlays",
      "passport",
      "passports",
      "secure document",
      "secure identity",
      "smart card",
      "smart cards",
    ],
    protectedPagePatterns: [
      "/en/news-events/",
    ],
    protectedInclude: [
      "credential",
      "credentials",
      "eid",
      "identity",
      "identity documents",
      "inlay",
      "passport",
      "secure document",
      "smart card",
    ],
    exclude: [
      "automotive",
      "energy",
      "fashion",
      "healthcare",
      "iot",
      "luxury",
      "payment",
      "payments",
      "telecom",
    ],
  },
  {
    name: "VTT News and Stories",
    sourceKeys: ["vtt news and stories", "vttresearch.com/en/news-stories/news-and-stories"],
    rejectExactPaths: [
      "/en/news-stories/news-and-stories",
    ],
    rejectTitlePatterns: [
      "news and stories",
    ],
    include: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "biometric",
      "credential",
      "digital identity",
      "document security",
      "forgery",
      "hologram",
      "identity",
      "identity document",
      "optical security",
      "passport",
      "polycarbonate",
      "security feature",
      "security printing",
      "substrate",
    ],
    protectedPagePatterns: [
      "/en/news-stories/",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "document security",
      "digital identity",
      "identity document",
      "optical security",
      "passport",
      "security feature",
      "security printing",
    ],
    exclude: [
      "battery",
      "cellular",
      "construction",
      "hydrogen",
      "mobility",
      "quantum",
      "robotics",
      "telecom",
    ],
  },
];

export function getSourceRelevanceRule(feed) {
  const fingerprint = [
    feed?.name,
    feed?.rssUrl,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  return SOURCE_RELEVANCE_RULES.find((rule) =>
    rule.sourceKeys.some((sourceKey) => fingerprint.includes(sourceKey))
  ) || null;
}

function buildSourceTermPattern(term) {
  const normalizedTerm = String(term || "").trim().toLowerCase();
  if (!normalizedTerm) {
    return null;
  }

  const escaped = normalizedTerm
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/\s+/g, "[\\s\\-/&]+");

  return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, "i");
}

export function findSourceRuleMatches(text, terms = []) {
  return terms.filter((term) => {
    const pattern = buildSourceTermPattern(term);
    return pattern ? pattern.test(text) : false;
  });
}

function getArticlePath(article) {
  const rawUrl = String(article?.link || "").trim();
  if (!rawUrl) {
    return "";
  }

  try {
    const parsed = new URL(rawUrl, "https://example.invalid");
    const pathname = parsed.pathname.replace(/\/+$/, "") || "/";
    return pathname.toLowerCase();
  } catch {
    return rawUrl.split("?")[0].replace(/\/+$/, "").toLowerCase();
  }
}

function findRejectedPageMatches(rule, article) {
  const articlePath = getArticlePath(article);
  const title = String(article?.title || "").trim().toLowerCase();
  const rejectedExactPaths = (rule.rejectExactPaths || []).filter((path) =>
    articlePath === String(path || "").replace(/\/+$/, "").toLowerCase()
  );
  const rejectedPathPatterns = (rule.rejectPagePatterns || []).filter((pattern) =>
    articlePath.includes(String(pattern || "").toLowerCase())
  );
  const rejectedTitlePatterns = (rule.rejectTitlePatterns || []).filter((pattern) =>
    title.includes(String(pattern || "").toLowerCase())
  );

  return [
    ...rejectedExactPaths.map((match) => `path:${match}`),
    ...rejectedPathPatterns.map((match) => `path-pattern:${match}`),
    ...rejectedTitlePatterns.map((match) => `title:${match}`),
  ];
}

function articleMatchesProtectedPagePattern(rule, article) {
  const protectedPagePatterns = rule.protectedPagePatterns || [];
  if (!protectedPagePatterns.length) {
    return true;
  }

  const articlePath = getArticlePath(article);
  return protectedPagePatterns.some((pattern) =>
    articlePath.includes(String(pattern || "").toLowerCase())
  );
}

export function getSourceRelevanceAssessment(feed, article) {
  const rule = getSourceRelevanceRule(feed);
  if (!rule) {
    return {
      accepted: true,
      rule: null,
      includedTerms: [],
      excludedTerms: [],
      reason: "no-source-rule",
    };
  }

  const articleText = [
    article?.title,
    article?.link,
    article?.contentSnippet,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  const rejectedPageMatches = findRejectedPageMatches(rule, article);
  if (rejectedPageMatches.length) {
    return {
      accepted: false,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms: findSourceRuleMatches(articleText, rule.exclude),
      rejectedPageMatches,
      reason: `rejected-page:${rejectedPageMatches.join(", ")}`,
    };
  }

  const protectedText = [
    article?.title,
    article?.link,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  const protectedTerms = findSourceRuleMatches(protectedText, rule.protectedInclude || []);
  if (protectedTerms.length && articleMatchesProtectedPagePattern(rule, article)) {
    return {
      accepted: true,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms: findSourceRuleMatches(articleText, rule.exclude),
      protectedTerms,
      reason: `protected-source-term:${protectedTerms.join(", ")}`,
    };
  }

  const excludedTerms = findSourceRuleMatches(articleText, rule.exclude);
  if (excludedTerms.length) {
    return {
      accepted: false,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms,
      reason: `excluded-term:${excludedTerms.join(", ")}`,
    };
  }

  const includedTerms = findSourceRuleMatches(articleText, rule.include);
  return {
    accepted: includedTerms.length > 0,
    rule,
    includedTerms,
    excludedTerms: [],
    reason: includedTerms.length > 0 ? "included-term" : "missing-allowlist-term",
  };
}

export function articleMatchesSourceRelevanceRule(feed, article) {
  return getSourceRelevanceAssessment(feed, article).accepted;
}
