// These URL targets are created by social-share widgets, not by publishers as
// article permalinks. Reject them globally so a parser mistake cannot make a
// login or share page look like content from an otherwise good source.
const NON_ARTICLE_LINK_PATTERNS = Object.freeze([
  "linkedin.com/",
  "facebook.com/sharer",
  "x.com/intent/",
  "twitter.com/intent/",
  "wa.me/",
  "api.whatsapp.com/send",
]);

export const SOURCE_RELEVANCE_RULES = [
  {
    name: "Identity Week Press Releases",
    sourceKeys: [
      "identity week press releases",
      "identityweek.net/category/press-releases",
    ],
    // Identity Week also publishes general cyber-security and event promotion.
    // This feed is intentionally limited to articles with a concrete identity,
    // credential, document, biometric, verification or border-control focus.
    include: [
      "age verification",
      "authentication",
      "biometric",
      "biometrics",
      "border control",
      "credential",
      "credentials",
      "deepfake",
      "digital id",
      "digital identity",
      "document clearing",
      "document fraud",
      "document processing",
      "e-gate",
      "egate",
      "eidas",
      "electronic identity",
      "facial recognition",
      "fraud prevention",
      "identity",
      "identity document",
      "identity verification",
      "id scanner",
      "liveness",
      "passport",
      "passports",
      "secure document",
      "travel document",
      "travel documents",
      "verification",
    ],
    // A booth invitation is a sales promotion, even when it mentions a genuine
    // biometric product.  Keep the terms narrow so substantive event reporting
    // remains eligible when it has one of the identity terms above.
    exclude: [
      "booth",
      "idwa",
      "meet them on",
      "meet us at",
    ],
  },
  {
    // Biometric Update is a strong specialist publication, but it also covers
    // adjacent consumer-tech, privacy and general AI stories. Require a
    // concrete identity, credential or biometric signal rather than accepting
    // every article from the publication.
    name: "Biometric Update",
    sourceKeys: ["biometric update", "biometricupdate.com"],
    include: [
      "age assurance",
      "age verification",
      "ai fraud",
      "authentication",
      "biometric",
      "biometrics",
      "credential",
      "credentials",
      "digital id",
      "digital identity",
      "digital wallet",
      "document security",
      "document verification",
      "eidas",
      "eudi wallet",
      "facial recognition",
      "identity proofing",
      "identity verification",
      "liveness",
      "mobile driver license",
      "mobile driver's license",
      "passport",
      "passports",
      "verifiable credential",
      "verifiable credentials",
    ],
    exclude: [
      "autonomous agents",
      "consumer survey",
      "smart glasses",
      "super app",
    ],
  },
  {
    name: "ICAO Doc 9303",
    sourceKeys: ["icao doc 9303", "\"doc%209303\""],
    include: [
      "icao doc 9303",
      "doc 9303",
      "machine readable travel document",
      "machine-readable travel document",
      "mrtd",
      "emrtd",
      "passport chip",
      "passport standard",
      "passport standards",
    ],
    exclude: ["hotel", "holiday", "tourism", "travel deals"],
    excludeSources: ["news.google.com", "bing.com", "head topics", "msn"],
  },
  {
    name: "ICAO Digital Travel Credential",
    sourceKeys: ["icao digital travel credential", "digital%20travel%20credential"],
    include: [
      "digital travel credential",
      "digital travel credentials",
      "icao dtc",
      "digital passport",
      "digital travel document",
      "digital travel documents",
    ],
    exclude: ["hotel", "holiday", "tourism", "travel deals"],
    excludeSources: [
      "news.google.com",
      "bing.com",
      "applemagazine",
      "head topics",
      "msn",
      "outlook traveller",
      "travel and tour world",
      "travel daily media",
      "travel wires",
    ],
  },
  {
    name: "ICAO PKD",
    sourceKeys: ["icao pkd", "icao%20pkd"],
    include: [
      "icao pkd",
      "public key directory",
      "passport authentication",
      "passport verification",
      "document signer certificate",
      "csca",
    ],
    exclude: ["hotel", "holiday", "tourism", "travel deals"],
    excludeSources: ["news.google.com", "bing.com", "head topics", "msn"],
  },
  {
    name: "ICAO Traveller Identification Programme",
    sourceKeys: ["icao traveller identification programme", "traveller%20identification%20programme"],
    include: [
      "traveller identification programme",
      "traveler identification program",
      "icao trip",
      "traveller identification",
      "traveler identification",
    ],
    exclude: ["hotel", "holiday", "tourism", "travel deals"],
    excludeSources: ["news.google.com", "bing.com", "head topics", "msn"],
  },
  {
    name: "Dutch IND Residence Updates",
    sourceKeys: ["dutch ind residence updates", "ind.nl/en/news"],
    include: [
      "asylum application",
      "biometric residence",
      "evisa",
      "residence card",
      "residence permit",
      "residence permits",
      "travel document",
      "visa",
      "visas",
    ],
    exclude: ["business newsletter", "newsletter is online"],
  },
  {
    name: "UKVI Residence Documents",
    sourceKeys: [
      "ukvi brp and brc guidance",
      "ukvi biometric residence permits",
      "biometric+residence+permit",
    ],
    include: [
      "biometric residence card",
      "biometric residence permit",
      "brc",
      "brp",
      "digital immigration status",
      "evisa",
      "share code",
    ],
    exclude: ["student visa", "sponsor licence", "sponsor license", "points-based immigration", "no deal brexit"],
  },
  {
    name: "SIGNE Security Documents",
    sourceKeys: ["signe security documents", "signe.es/feed"],
    include: [
      "anti-counterfeit",
      "anti-fraud",
      "anti-fraude",
      "authentication",
      "banking document",
      "banking documents",
      "banknote",
      "banknotes",
      "blockchain traceability",
      "cheque",
      "cheques",
      "certificado académico",
      "certificados académicos",
      "digital identity",
      "document fraud",
      "document security",
      "documento bancario",
      "documentos bancarios",
      "documento de identidad",
      "documentos de identidad",
      "documento de viaje",
      "documentos de viaje",
      "documento seguro",
      "documentos seguros",
      "electronic signature",
      "e-signature",
      "firma electrónica",
      "forgery",
      "falsificación",
      "hologram",
      "holograms",
      "holograma",
      "hologramas",
      "identity card",
      "identity document",
      "identity documents",
      "identidad digital",
      "impresión de seguridad",
      "passport",
      "passports",
      "pasaporte",
      "pasaportes",
      "permiso de conducir",
      "permisos de conducir",
      "secure document",
      "secure documents",
      "security feature",
      "security features",
      "security printing",
      "seguridad documental",
      "tarjeta de identidad",
      "tarjetas de identidad",
      "título universitario",
      "títulos universitarios",
      "travel document",
      "travel documents",
      "video identification",
      "videoidentificación",
      "visa",
      "visas",
      "visado",
      "visados",
    ],
    protectedInclude: [
      "anti-fraude",
      "documento de identidad",
      "documentos de identidad",
      "documento de viaje",
      "documentos de viaje",
      "documento seguro",
      "documentos seguros",
      "firma electrónica",
      "falsificación",
      "holograma",
      "hologramas",
      "identidad digital",
      "impresión de seguridad",
      "pasaporte",
      "pasaportes",
      "seguridad documental",
      "tarjeta de identidad",
      "tarjetas de identidad",
      "título universitario",
      "títulos universitarios",
      "videoidentificación",
      "visado",
      "visados",
    ],
    exclude: [
      "award",
      "awards",
      "career",
      "careers",
      "evento",
      "eventos",
      "event",
      "events",
      "feria",
      "ferias",
      "fondos europeos",
      "industria 4.0",
      "job",
      "jobs",
      "premio",
      "premios",
      "responsabilidad social",
      "rsc",
      "sostenibilidad",
      "sustainability",
      "webinar",
    ],
  },
  {
    name: "OFS Security Printing Insights",
    sourceKeys: ["ofs security printing insights", "ofs.ch/en/insights"],
    include: [
      "anti-counterfeit",
      "banknote",
      "banknotes",
      "currency",
      "hologram",
      "identity document",
      "identity documents",
      "passport",
      "passports",
      "security feature",
      "security features",
      "security printing",
      "secure document",
      "secure documents",
      "visa",
      "visas",
    ],
    exclude: ["career", "careers", "job", "jobs", "sustainability", "webinar"],
  },
  {
    name: "Jura Security Printing",
    sourceKeys: ["jura security printing", "jura.hu/feed"],
    include: [
      "banknote",
      "banknotes",
      "border management",
      "currency",
      "identity",
      "identity document",
      "passport",
      "security printing",
      "tax stamp",
      "trusteCH",
    ],
    exclude: ["career", "careers", "job", "jobs"],
  },
  {
    name: "Koenig & Bauer Banknote Solutions",
    sourceKeys: ["koenig & bauer banknote solutions", "banknote-solutions.koenig-bauer.com/en/feed.rss"],
    include: [
      "authentication",
      "banknote",
      "banknotes",
      "banknote solutions",
      "currency",
      "currency production",
      "security feature",
      "security features",
      "security printing",
      "security printer",
      "vision & protection",
      "vision and protection",
      "valicash",
    ],
    exclude: ["commercial printing", "corrugated", "packaging", "sheetfed"],
  },
  {
    name: "Austrian State Printing Office News",
    sourceKeys: ["austrian state printing office news", "staatsdruckerei.at/en/osd-news/feed"],
    include: [
      "biometric",
      "biometrics",
      "digital identity",
      "digital wallet",
      "driving licence",
      "driving license",
      "e-passport",
      "identity card",
      "identity document",
      "identity documents",
      "passport",
      "passports",
      "personalisation system",
      "personalization system",
      "secure identity",
      "travel document",
      "visa",
      "visas",
    ],
    exclude: ["career", "careers", "job", "jobs", "theme day"],
  },
  {
    name: "Missouri DMV",
    sourceKeys: ["missouri dmv", "dor.mo.gov/news/rss"],
    include: [
      "commercial driver license",
      "driver license",
      "driver licenses",
      "driver's license",
      "driver’s license",
      "nondriver id card",
      "real id",
      "temporary driver license",
    ],
    exclude: [],
  },
  {
    name: "Nebraska DMV",
    sourceKeys: ["nebraska dmv", "dmv.nebraska.gov/rss/news"],
    include: [
      "driver license and id card",
      "driver license and state id",
      "driver license services",
      "driver's license and id",
      "driver’s license and id",
      "issuance of credentials",
      "real id",
      "temporary driver license",
      "tracks driver's license and id",
      "tracks driver’s license and id",
    ],
    exclude: [],
  },
  {
    name: "Veridos Press & Media",
    sourceKeys: ["veridos press & media", "veridos.com/en/about/press-media"],
    rejectPagePatterns: [
      "/home.html",
      "/career",
      "/careers",
      "/downloads",
      "/imprint",
      "/projects",
      "/support",
    ],
    rejectExactPaths: [
      "/en",
      "/home",
      "/en/home",
      "/en/home.html",
      "/en/about/press-media",
      "/en/about/press-media/press-releases",
    ],
    rejectTitlePatterns: [
      "careers",
      "downloads",
      "home",
      "imprint",
      "projects",
      "support",
    ],
    include: [
      "credential",
      "credentials",
      "eid",
      "government identity",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "secure identities",
      "secure identity",
      "travel document",
      "travel documents",
    ],
    exclude: [
      "career",
      "careers",
      "download",
      "downloads",
      "imprint",
      "job",
      "jobs",
      "project overview",
      "support",
    ],
  },
  {
    name: "IN Groupe Newsroom",
    sourceKeys: ["in groupe newsroom", "ingroupe.com/newsroom"],
    rejectPagePatterns: [
      "/a-global-company",
      "/about",
      "/brands",
      "/company",
      "/customer-case",
      "/customer-cases",
      "/customers",
      "/dsar",
      "/group",
      "/integrity-and-compliance",
      "/innovation",
      "/leadership",
      "/media-library",
      "/mediatheque",
      "/newsroom/media",
      "/purpose",
      "/responsibility",
      "/strategy",
      "/values",
      "/values-purpose",
      "/vision-and-strategy",
      "/you-are-government",
      "/you-are-business",
    ],
    rejectExactPaths: [
      "/newsroom",
      "/en/newsroom",
      "/fr/newsroom",
    ],
    rejectTitlePatterns: [
      "corporate responsibility",
      "customer case",
      "customer cases",
      "data subject access request",
      "media library",
      "new organization and executive committee",
      "the group brands",
      "newsroom",
      "welcome to our media library",
      "welcome to our newsroom",
      "we help governments assert their sovereignty",
    ],
    include: [
      "credential",
      "credentials",
      "banknote",
      "banknotes",
      "digital identity",
      "eid",
      "government identity",
      "identities",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "secure identity",
      "secure identities",
      "security thread",
    ],
    exclude: [
      "compliance",
      "corporate responsibility",
      "customer case",
      "customer cases",
      "media library",
      "values and purpose",
      "vision and strategy",
    ],
  },
  {
    name: "HID Press Releases",
    sourceKeys: ["hid press releases", "newsroom.hidglobal.com/press-releases"],
    rejectPagePatterns: [
      "/es/press-releases",
      "/pt/press-releases",
      "/de/press-releases",
      "/fr/press-releases",
    ],
    rejectExactPaths: [
      "/press-releases",
      "/en/press-releases",
      "/es/press-releases",
      "/pt/press-releases",
      "/de/press-releases",
      "/fr/press-releases",
    ],
    rejectTitlePatterns: [
      "press releases",
    ],
    include: [
      "credential",
      "credentials",
      "document",
      "documents",
      "eid",
      "government id",
      "government identity",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure identity",
      "secure identities",
    ],
    exclude: [
      "commercial launch",
      "embedded application environment",
      "mercury security",
      "press release index",
      "school safety",
    ],
  },
  {
    name: "SICPA Newsroom",
    sourceKeys: ["sicpa newsroom", "sicpa.com/all-press-releases"],
    include: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "digital identity",
      "digital identity wallet",
      "digital passport",
      "digital travel credential",
      "eid",
      "excise stamp",
      "identity document",
      "id document",
      "passport",
      "passports",
      "secure document",
      "security printing",
      "sovereign solutions",
      "tax stamp",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "digital identity wallet",
      "digital passport",
      "digital travel credential",
      "eid",
      "excise stamp",
      "identity document",
      "id document",
      "passport",
      "passports",
      "secure document",
      "security printing",
      "tax stamp",
    ],
    exclude: [
      "campus",
      "community",
      "corporate social responsibility",
      "csr",
      "education",
      "erp",
      "fuel integrity",
      "fuel marking",
      "minergie",
      "sap",
      "sustainability report",
      "underserved communities",
      "water scarcity",
    ],
  },
  {
    name: "G+D Press Releases",
    sourceKeys: ["g+d press releases", "gi-de.com/en/about-us/press/press-releases"],
    rejectPagePatterns: [
      "/about-us/ventures",
      "/currency-technology/currency-management",
      "/currency-technology/software",
      "/currency-technology/cash",
      "/identity-technologies/veridos",
      "/ventures",
      "/veridos",
    ],
    rejectExactPaths: [
      "/en",
      "/en/about-us/press/press-releases",
    ],
    rejectTitlePatterns: [
      "end-to-end cash and currency management",
      "g+d ventures",
      "secure cash management software",
      "veridos - your trusted identity partner",
    ],
    include: [
      "authentication",
      "banknote",
      "banknotes",
      "cash",
      "credential",
      "credentials",
      "currency",
      "government identity",
      "identity",
      "identity documents",
      "identity technology",
      "passport",
      "passports",
      "public sector identity",
      "secure document",
      "secure documents",
      "secure identities",
      "secure identity",
      "security printing",
      "sovereign solutions",
      "veridos",
      "xtec",
    ],
    exclude: [
      "5g",
      "asset tracking",
      "banking market",
      "cloud-based remote esim",
      "compliance expert",
      "connected car",
      "connectivity",
      "crypto",
      "digital payments",
      "esim",
      "e-sim",
      "iot",
      "mobile ticketing",
      "netcetera",
      "payment security",
      "payment",
      "payments",
      "rabo investments",
      "remote esim",
      "rivian",
      "secunet",
      "sim",
      "telecom",
      "telecommunications",
      "trusted software",
      "wearable",
    ],
  },
  {
    name: "Crane Currency News & Insights",
    sourceKeys: ["crane currency news & insights", "cranecurrency.com/news-insights"],
    rejectPagePatterns: [
      "/media/",
      "/solutions/",
    ],
    rejectExactPaths: [
      "/news-insights",
    ],
    rejectTitlePatterns: [
      "news & insights",
    ],
    include: [
      "anti-counterfeit",
      "banknote",
      "banknotes",
      "banknote design",
      "cash",
      "cash cycle",
      "central bank",
      "counterfeit",
      "currency manager",
      "detect",
      "issuing authority",
      "micro optic",
      "micro-optic",
      "micro optics",
      "motion",
      "motion surface",
      "polymer",
      "rapid",
      "security feature",
      "security features",
      "security thread",
      "substrate",
    ],
    protectedPagePatterns: [
      "/news-insights/",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "banknote",
      "banknotes",
      "banknote design",
      "cash",
      "cash cycle",
      "central bank",
      "counterfeit",
      "currency manager",
      "issuing authority",
      "micro optic",
      "micro-optic",
      "micro optics",
      "motion surface",
      "polymer",
      "rapid",
      "security feature",
      "security features",
      "security thread",
    ],
    exclude: [
      "anniversary",
      "community",
      "donation",
      "facility",
      "generic company news",
      "solar farm",
      "sustainability",
    ],
  },
  {
    name: "KURZ Press Releases",
    sourceKeys: ["kurz press releases", "kurz-world.com/en/newsroom/press"],
    include: [
      "anti-counterfeit",
      "anticounterfeit",
      "banknote",
      "banknotes",
      "card",
      "cards",
      "counterfeit",
      "counterfeits",
      "currency",
      "forgeries",
      "forgery",
      "high security",
      "hologram",
      "holograms",
      "holography",
      "identity",
      "ovd",
      "optical security",
      "secure document",
      "secure documents",
      "security feature",
      "security features",
      "security printing",
      "trustseal",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "anticounterfeit",
      "banknote",
      "banknotes",
      "counterfeit protection",
      "counterfeit",
      "counterfeits",
      "forgeries",
      "forgery",
      "hologram",
      "holograms",
      "holography",
      "ovd",
      "security against counterfeits",
      "security feature",
      "security features",
      "security printing",
    ],
    exclude: [
      "automotive",
      "beverage",
      "brand enhancement",
      "consumer electronics",
      "cosmetics",
      "decoration",
      "decorative",
      "decorative finishing",
      "embellishment",
      "home appliances",
      "jersey",
      "labels",
      "luxe pack",
      "mobility",
      "packaging",
      "pentawards",
      "rpet",
      "spirits",
      "surface finishing",
      "textile",
      "textiles",
      "vestel",
      "wine",
      "wine & spirits",
    ],
  },
  {
    name: "OVD Kinegram Insights",
    sourceKeys: ["ovd kinegram insights", "kinegram.com/events-insights/insights"],
    rejectExactPaths: [
      "/events-insights/insights",
    ],
    rejectTitlePatterns: [
      "news and insights by ovd kinegram",
    ],
    include: [
      "card",
      "cards",
      "credential",
      "document security",
      "government document",
      "government documents",
      "hologram",
      "holography",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "kinegram",
      "ovd",
      "passport",
      "passports",
      "polycarbonate",
      "secure document",
      "secure documents",
      "security feature",
      "security features",
      "travel document",
      "travel documents",
    ],
    protectedPagePatterns: [
      "/events-insights/insights/",
    ],
    protectedInclude: [
      "document security",
      "government documents",
      "hologram",
      "identity document",
      "identity documents",
      "id card",
      "kinegram",
      "ovd",
      "passport",
      "passports",
      "polycarbonate",
      "security feature",
      "security features",
    ],
    exclude: [
      "career",
      "careers",
      "event registration",
      "job",
      "jobs",
      "newsletter",
    ],
  },
  {
    name: "Louisenthal Press Releases",
    sourceKeys: ["louisenthal press releases", "louisenthal.com/highlights/news/press-releases"],
    rejectExactPaths: [
      "/highlights/news/press-releases",
    ],
    rejectTitlePatterns: [
      "press releases",
    ],
    include: [
      "banknote",
      "banknotes",
      "currency",
      "holography",
      "iaca",
      "security feature",
      "security features",
      "security foil",
      "security thread",
      "substrate",
      "varifeye",
    ],
    protectedPagePatterns: [
      "/highlights/news/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "holography",
      "security feature",
      "security features",
      "security foil",
      "security thread",
      "substrate",
    ],
    exclude: [
      "automotive",
      "car heating",
      "interior heating",
      "newsletter",
    ],
  },
  {
    name: "Koenig & Bauer Newsroom",
    sourceKeys: ["koenig & bauer newsroom", "koenig-bauer.com/en/newsroom", "koenig-bauer.com/en/newsroom/press-releases"],
    rejectExactPaths: [
      "/en/newsroom",
      "/en/newsroom/press-releases",
    ],
    rejectTitlePatterns: [
      "koenig & bauer newsroom",
      "newsletter subscription",
      "press contacts",
    ],
    include: [
      "authentication",
      "banknote",
      "banknotes",
      "banknote solutions",
      "brand protection",
      "currency",
      "currency production",
      "invisible security features",
      "security printing",
      "security print",
      "security printer",
      "security features",
      "vision & protection",
      "vision and protection",
      "valicash",
    ],
    protectedPagePatterns: [
      "/en/newsroom/press-releases/article/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "banknote solutions",
      "brand protection",
      "currency production",
      "invisible security features",
      "security printing",
      "security features",
      "vision & protection",
      "vision and protection",
      "valicash",
    ],
    exclude: [
      "annual report",
      "commercial printing",
      "corrugated",
      "packaging",
      "sheetfed",
      "sports",
    ],
  },
  {
    name: "IDEMIA Pressroom",
    sourceKeys: ["idemia pressroom", "idemia.com/pressroom"],
    rejectExactPaths: [
      "/pressroom",
    ],
    rejectTitlePatterns: [
      "pressroom",
      "spokespersons",
    ],
    include: [
      "biometric",
      "biometrics",
      "civil identity",
      "credential",
      "credentials",
      "digital identity",
      "driver license",
      "driver licenses",
      "driving licence",
      "identity",
      "identity verification",
      "id card",
      "id cards",
      "mobile id",
      "passport",
      "passports",
      "public security",
      "secure identity",
      "secure transactions",
      "tsa precheck",
      "wallet",
    ],
    protectedInclude: [
      "biometric",
      "civil identity",
      "digital identity",
      "driver license",
      "driver licenses",
      "identity verification",
      "mobile id",
      "public security",
      "tsa precheck",
    ],
    exclude: [
      "fan experience",
      "iot",
      "la metro",
      "music cards",
      "nickel music",
      "payment card",
      "payment cards",
      "payments",
      "secure transactions powers",
      "sim",
      "tokenization",
    ],
  },
  {
    name: "Thales Digital Identity Newsroom",
    sourceKeys: ["thales digital identity newsroom", "cpl.thalesgroup.com/about-us/newsroom"],
    rejectExactPaths: [
      "/about-us/newsroom",
    ],
    rejectTitlePatterns: [
      "search news release",
      "newsroom",
    ],
    include: [
      "access management",
      "authentication",
      "credential",
      "credentials",
      "digital identity",
      "document verification",
      "identity",
      "identity platform",
      "identity verification",
      "onboarding",
      "onewelcome",
      "passwordless",
      "public sector",
    ],
    protectedInclude: [
      "digital identity",
      "identity platform",
      "identity verification",
      "onewelcome",
      "public sector",
    ],
    exclude: [
      "ai adoption",
      "ai insider threat",
      "bad bot",
      "cybersecurity",
      "data threat",
      "enterprise ai",
      "google cloud",
      "imperva",
      "iot",
    ],
  },
  {
    name: "PWPW RSS",
    sourceKeys: ["pwpw rss", "pwpw.pl/en/rss"],
    include: [
      "banknote",
      "banknotes",
      "card",
      "cards",
      "document",
      "documents",
      "eid",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "security printing",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "identity card",
      "identity document",
      "id card",
      "passport",
      "secure document",
      "security printing",
    ],
    exclude: [
      "anniversary",
      "career",
      "careers",
      "historical tribute",
      "insurgent",
      "insurgents",
      "job",
      "jobs",
      "procurement",
      "tribute paid",
      "tender unrelated",
    ],
  },
  {
    name: "Atlantic Zeiser News",
    sourceKeys: ["atlantic zeiser news", "atlanticzeiser.com/en/news"],
    rejectExactPaths: [
      "/en/news",
    ],
    rejectTitlePatterns: [
      "atlantic zeiser news",
      "latest news",
    ],
    include: [
      "banknote",
      "banknotes",
      "card personalization",
      "currency",
      "document",
      "documents",
      "identity document",
      "id card",
      "passport",
      "secure document",
      "security printing",
      "track and trace",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "card personalization",
      "identity document",
      "security printing",
      "track and trace",
    ],
    exclude: [
      "coding and marking",
      "cosmetics",
      "industrial printing",
      "packaging",
      "pharma packaging",
      "serialization only",
    ],
  },
  {
    name: "Mühlbauer Press",
    sourceKeys: [
      "mühlbauer press",
      "muehlbauer press",
      "muehlbauer.de/company/company/press",
      "muehlbauer.de/news-events/news",
    ],
    rejectExactPaths: [
      "/company/company/press",
      "/news-events/news",
    ],
    rejectTitlePatterns: [
      "mühlbauer press",
      "press releases",
    ],
    include: [
      "biometric",
      "biometrics",
      "document verification",
      "eid",
      "government solution",
      "government solutions",
      "identity",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure document",
      "secure documents",
    ],
    protectedInclude: [
      "biometric",
      "document verification",
      "government solution",
      "identity document",
      "id card",
      "passport",
      "secure document",
    ],
    exclude: [
      "battery",
      "display",
      "emobility",
      "semiconductor",
      "smart factory",
      "solar",
    ],
  },
  {
    name: "MaskTech Press",
    sourceKeys: ["masktech press", "masktech.com/press/60/en"],
    rejectExactPaths: [
      "/press/60/en",
    ],
    include: [
      "eid",
      "electronic identity",
      "government id",
      "government identity",
      "identity",
      "identity card",
      "identity document",
      "id card",
      "national id",
      "secure chip",
      "secure identity",
      "smart card",
    ],
    protectedInclude: [
      "eid",
      "electronic identity",
      "government id",
      "identity card",
      "identity document",
      "national id",
      "secure identity",
      "smart card",
    ],
    exclude: [
      "career",
      "careers",
      "job",
      "jobs",
    ],
  },
  {
    name: "Daon Resources",
    sourceKeys: ["daon resources", "daon.com/feed", "daon.com/resources"],
    rejectExactPaths: [
      "/resources",
    ],
    include: [
      "authentication",
      "biometric",
      "biometrics",
      "digital identity",
      "document verification",
      "identity proofing",
      "identity verification",
      "kyc",
      "liveness",
      "onboarding",
      "passwordless",
      "verification",
    ],
    protectedInclude: [
      "biometric",
      "digital identity",
      "document verification",
      "identity proofing",
      "identity verification",
      "kyc",
      "liveness",
      "onboarding",
    ],
    exclude: [
      "webinar replay only",
      "workforce only",
    ],
  },
  {
    name: "GenKey News",
    sourceKeys: ["genkey news", "genkey.com/news"],
    rejectExactPaths: [
      "/news",
    ],
    include: [
      "biometric",
      "biometrics",
      "civil registry",
      "enrollment",
      "enrolment",
      "government identity",
      "identity",
      "identity management",
      "national id",
      "voter",
      "voter registration",
    ],
    protectedInclude: [
      "biometric",
      "biometrics",
      "civil registry",
      "government identity",
      "identity management",
      "national id",
      "voter registration",
    ],
    exclude: [
      "career",
      "careers",
      "job",
      "jobs",
    ],
  },
  {
    name: "Bundesdruckerei Press Releases",
    sourceKeys: ["bundesdruckerei press releases", "bundesdruckerei.de/en/newsroom/press-releases"],
    rejectPagePatterns: [
      "/antragsportal",
      "/d-trust/portal",
      "/ehealth-antragsportal",
      "/fields-of-use",
      "/fields-use",
      "/group",
      "/portal",
      "/solutions",
      "/trust-services",
    ],
    rejectExactPaths: [
      "/de",
      "/en/newsroom",
      "/en/newsroom/latest-news",
      "/en/newsroom/press-releases",
    ],
    rejectTitlePatterns: [
      "d-trust ehealth antragsportal",
      "d-trust portal",
      "latest news",
      "press releases of the bundesdruckerei-group",
    ],
    include: [
      "ausweis",
      "banknote",
      "banknotes",
      "d-trust",
      "eid",
      "government identity",
      "government solutions",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "secure identities",
      "secure identity",
      "security printing",
      "self-sovereign identity",
      "trust service",
      "trust services",
    ],
    protectedPagePatterns: [
      "/newsroom/press-releases/",
      "/newsroom/pressemitteilungen/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "banknote of the future",
      "concept banknote",
      "eid",
      "identity document",
      "identity documents",
      "id card",
      "id cards",
      "passport",
      "passports",
      "quantum computers",
      "secure identity document",
      "secure identity documents",
      "security printing",
    ],
    exclude: [
      "accessibility",
      "accessibility statement",
      "adva network",
      "company restructures",
      "company structure",
      "cooperates with start-ups",
      "corporate",
      "corporate governance",
      "event",
      "events",
      "genua",
      "group structure",
      "innovation hub",
      "industrial remote maintenance",
      "management board",
      "remote maintenance",
      "secunet",
      "start-ups",
      "supervisory board",
      "telematics infrastructure",
      "whistleblowing",
    ],
  },
  {
    name: "ICAO Newsroom",
    sourceKeys: ["icao newsroom", "icao.int/news"],
    rejectPagePatterns: [
      "/es/news",
      "/fr/news",
      "/social-media",
      "/media-accreditation",
      "/council-president",
    ],
    rejectExactPaths: [
      "/news",
    ],
    rejectTitlePatterns: [
      "icao newsroom",
      "icao tv",
      "social media",
      "media accreditation",
      "council president",
      "sala de prensa",
      "salle des nouvelles",
    ],
    include: [
      "border interoperability",
      "digital travel credential",
      "doc 9303",
      "emrtd",
      "icao pkd",
      "identity",
      "machine readable",
      "mrtd",
      "mrz",
      "passport",
      "passports",
      "pkd",
      "travel credential",
      "travel document",
      "travel documents",
      "traveller identification programme",
    ],
    protectedPagePatterns: [
      "/news/",
    ],
    protectedInclude: [
      "digital travel credential",
      "doc 9303",
      "passport",
      "pkd",
      "travel document",
    ],
    exclude: [
      "assembly",
      "aviation safety",
      "climate",
      "runway",
      "security council",
    ],
  },
  {
    name: "ICAO TRIP",
    sourceKeys: ["icao trip", "icao.int/facilitation-programmes/assistance"],
    rejectPagePatterns: [
      "/icao.tv",
      "/social-media",
      "/strategic-goals/",
      "/finvest",
      "/corsia",
      "/state-action-plans-and-assistance",
      "/linkedin",
      "linkedin.com",
      "unitingaviation.com",
    ],
    rejectExactPaths: [
      "/facilitation-programmes/assistance",
    ],
    rejectTitlePatterns: [
      "icao tv",
      "linkedin",
      "unitingaviation",
      "transformational objective",
      "finvest hub",
      "aviation is environmentally sustainable",
      "every flight is safe and secure",
    ],
    include: [
      "border control",
      "border interoperability",
      "digital travel credential",
      "doc 9303",
      "emrtd",
      "icao pkd",
      "identity management",
      "machine readable",
      "mrtd",
      "mrz",
      "passport",
      "passports",
      "pkd",
      "public key directory",
      "travel credential",
      "travel document",
      "travel documents",
      "traveller identification programme",
    ],
    protectedPagePatterns: [
      "/facilitation-programmes/assistance/",
      "/news/",
    ],
    protectedInclude: [
      "border control",
      "digital travel credential",
      "doc 9303",
      "passport",
      "pkd",
      "public key directory",
      "travel document",
      "traveller identification programme",
    ],
    exclude: [
      "aviation environment",
      "climate",
      "co2 reduction",
      "corsia",
      "extraordinary assembly",
      "gender summit",
      "global air transport",
      "linkedin",
      "runway",
      "safety",
      "social media",
      "tv",
      "unitingaviation",
    ],
  },
  {
    name: "CBP Newsroom",
    sourceKeys: ["cbp newsroom", "cbp.gov/newsroom", "cbp.gov/newsroom/media-releases/all"],
    rejectPagePatterns: [
      "/250",
      "/travel/",
      "/trusted-traveler-programs/",
    ],
    rejectExactPaths: [
      "/newsroom",
      "/newsroom/media-releases",
      "/newsroom/media-releases/all",
      "/newsroom/accountability-and-transparency",
      "/newsroom/announcements",
      "/newsroom/cbp-live",
      "/newsroom/communicados-de-prensa",
      "/newsroom/documents-library",
      "/newsroom/frontline-digital-magazine",
      "/newsroom/legal-notices",
      "/newsroom/media-releases/all/",
      "/newsroom/multimedia-libraries",
      "/newsroom/publications-catalog",
      "/newsroom/social-media-directory",
      "/newsroom/stats-and-summaries",
    ],
    rejectTitlePatterns: [
      "media releases",
      "newsroom",
    ],
    include: [
      "biometric",
      "biometrics",
      "border",
      "border crossing",
      "entry/exit",
      "entry exit system",
      "entry exit",
      "facial recognition",
      "global entry",
      "inspection",
      "mobile passport control",
      "passport",
      "passports",
      "travel document",
      "travel documents",
      "traveler",
      "travellers",
      "trusted traveler",
      "trusted travellers",
      "visa",
      "visas",
    ],
    protectedPagePatterns: [
      "/newsroom/announcements/",
      "/newsroom/local-media-release/",
      "/newsroom/media-release/",
      "/newsroom/media-releases/",
      "/newsroom/national-media-release/",
    ],
    protectedInclude: [
      "biometric",
      "border",
      "facial recognition",
      "mobile passport control",
      "passport",
      "trusted traveler",
      "visa",
    ],
    exclude: [
      "cash seizure",
      "accreditation",
      "academy seeks",
      "counterfeit merchandise",
      "cocaine",
      "fentanyl",
      "firearms",
      "marijuana",
      "methamphetamine",
      "narcotics",
      "seized",
      "seizure",
    ],
  },
  {
    name: "GOV.UK News and Communications",
    sourceKeys: [
      "gov.uk news and communications",
      "gov.uk/search/news-and-communications",
      "ukvi biometric residence permits",
      "gov.uk/biometric-residence-permits",
      "ukvi brp and brc guidance",
      "gov.uk/government/publications/biometric-residence-permits-guidance",
    ],
    rejectExactPaths: [
      "/biometric-residence-permits",
      "/government/publications/biometric-residence-permits-guidance",
      "/search/news-and-communications",
    ],
    rejectTitlePatterns: [
      "biometric residence permits",
      "biometric residence permits guidance",
      "news and communications",
    ],
    include: [
      "biometric residence permit",
      "biometric residence permits",
      "biometric residence card",
      "biometric residence cards",
      "border",
      "digital immigration status",
      "evisa",
      "home office",
      "identity document",
      "immigration",
      "passport",
      "passports",
      "residence permit",
      "residence permits",
      "travel document",
      "travel documents",
      "ukvi",
      "visa",
      "visas",
    ],
    protectedPagePatterns: [
      "/government/collections/",
      "/government/news/",
      "/government/publications/",
      "/government/speeches/",
    ],
    protectedInclude: [
      "biometric residence permit",
      "evisa",
      "immigration",
      "passport",
      "residence permit",
      "travel document",
      "ukvi",
      "visa",
    ],
    exclude: [
      "farming",
      "flood",
      "hospital",
      "nhs",
      "school",
      "tax",
      "transport",
    ],
  },
  {
    name: "Landqart News",
    sourceKeys: ["landqart news", "landqart.com/en/stories/news"],
    rejectExactPaths: [
      "/en/stories/news",
    ],
    rejectTitlePatterns: [
      "news",
    ],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "central bank",
      "currency",
      "passport",
      "passports",
      "security paper",
      "security substrate",
      "substrate",
      "thread",
      "threads",
      "watermark",
    ],
    protectedPagePatterns: [
      "/en/stories/news/",
    ],
    protectedInclude: [
      "banknote",
      "banknotes",
      "central bank",
      "currency",
      "passport",
      "security paper",
      "substrate",
      "watermark",
    ],
    exclude: [
      "award",
      "anniversary",
      "career",
      "careers",
      "csr",
      "graduate",
      "job",
      "jobs",
      "sustainability",
    ],
  },
  {
    name: "POLYVANTIS Press",
    sourceKeys: ["polyvantis press", "polyvantis.com/en/press"],
    rejectExactPaths: [
      "/en/press",
    ],
    rejectTitlePatterns: [
      "press",
    ],
    include: [
      "border control",
      "credential",
      "credentials",
      "eid",
      "government identity",
      "identity",
      "identity card",
      "identity cards",
      "identity document",
      "identity documents",
      "id card",
      "passports",
      "polycarbonate",
      "secure document",
      "secure documents",
      "security feature",
      "traffic control",
      "travel document",
    ],
    protectedPagePatterns: [
      "/en/press/",
    ],
    protectedInclude: [
      "credential",
      "eid",
      "identity document",
      "identity documents",
      "polycarbonate",
      "secure document",
      "security feature",
      "travel document",
    ],
    exclude: [
      "aquarium",
      "automotive",
      "construction",
      "furniture",
      "interior",
      "retail display",
      "store fixture",
    ],
  },
  {
    name: "Linxens News & Events",
    sourceKeys: ["linxens news & events", "linxens.com/en/news-events"],
    rejectExactPaths: [
      "/en/news-events",
    ],
    rejectTitlePatterns: [
      "news & events",
    ],
    include: [
      "authentication",
      "biometric",
      "biometrics",
      "credential",
      "credentials",
      "eid",
      "embedded security",
      "government identity",
      "identity",
      "identity documents",
      "inlay",
      "inlays",
      "passport",
      "passports",
      "secure document",
      "secure identity",
      "smart card",
      "smart cards",
    ],
    protectedPagePatterns: [
      "/en/news-events/",
    ],
    protectedInclude: [
      "credential",
      "credentials",
      "eid",
      "identity",
      "identity documents",
      "inlay",
      "passport",
      "secure document",
      "smart card",
    ],
    exclude: [
      "automotive",
      "energy",
      "fashion",
      "healthcare",
      "iot",
      "luxury",
      "payment",
      "payments",
      "telecom",
    ],
  },
  {
    // Frontex publishes wider institutional and maritime material alongside
    // operational border intelligence. Require a concrete border, document or
    // migration-enforcement signal before it can enter a profile candidate set.
    name: "Frontex Newsroom",
    sourceKeys: ["frontex newsroom", "frontex.europa.eu/media-centre/news"],
    include: [
      "border control",
      "border guard",
      "border guards",
      "border management",
      "border surveillance",
      "document fraud",
      "document inspection",
      "entry/exit system",
      "entry exit system",
      "etias",
      "identity check",
      "migrant smuggling",
      "passport",
      "passports",
      "travel document",
      "travel documents",
      "trafficking in human beings",
    ],
    exclude: [
      "maritime exercise",
      "coast guard",
      "annual report",
      "award ceremony",
      "procurement notice",
    ],
  },
  {
    // eu-LISA's news page also contains governance and internal IT updates.
    // Keep only systems and technology that underpin travel documents, border
    // processing, visas or identity interoperability.
    name: "eu-LISA Updates",
    sourceKeys: ["eu-lisa updates", "eulisa.europa.eu/news-and-events"],
    include: [
      "biometric",
      "biometrics",
      "border control",
      "border management",
      "document inspection",
      "entry/exit system",
      "entry exit system",
      "ees",
      "etias",
      "eurodac",
      "identity interoperability",
      "identity management",
      "interoperability",
      "passport",
      "passports",
      "schengen information system",
      "travel document",
      "travel documents",
      "visa information system",
    ],
    exclude: [
      "annual report",
      "data management",
      "industry roundtable",
      "management board",
      "procurement notice",
    ],
  },
  {
    name: "VTT News and Stories",
    sourceKeys: ["vtt news and stories", "vttresearch.com/en/news-stories/news-and-stories"],
    rejectExactPaths: [
      "/en/news-stories/news-and-stories",
    ],
    rejectTitlePatterns: [
      "news and stories",
    ],
    include: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "banknotes",
      "biometric",
      "credential",
      "digital identity",
      "document security",
      "forgery",
      "hologram",
      "identity",
      "identity document",
      "optical security",
      "passport",
      "polycarbonate",
      "security feature",
      "security printing",
      "substrate",
    ],
    protectedPagePatterns: [
      "/en/news-stories/",
    ],
    protectedInclude: [
      "anti-counterfeit",
      "authentication",
      "banknote",
      "document security",
      "digital identity",
      "identity document",
      "optical security",
      "passport",
      "security feature",
      "security printing",
    ],
    exclude: [
      "battery",
      "cellular",
      "construction",
      "hydrogen",
      "mobility",
      "quantum",
      "robotics",
      "telecom",
    ],
  },
  {
    name: "EU Commission Migration and Home Affairs News",
    sourceKeys: ["eu commission migration and home affairs news", "home-affairs.ec.europa.eu/news"],
    rejectExactPaths: [
      "/news",
      "/news_en",
    ],
    include: [
      "asylum",
      "border",
      "border control",
      "border management",
      "borders",
      "digital identity",
      "ees",
      "entry exit system",
      "eu-lisa",
      "european travel information and authorisation system",
      "external borders",
      "identity",
      "identity check",
      "internal security",
      "migration",
      "migrant smuggling",
      "passport",
      "passports",
      "residence permit",
      "schengen",
      "security",
      "travel document",
      "visa",
    ],
    protectedInclude: [
      "border",
      "border management",
      "ees",
      "entry exit system",
      "external borders",
      "identity check",
      "migrant smuggling",
      "schengen",
    ],
    exclude: [
      "newsletter",
      "subscribe",
    ],
  },
  {
    name: "Europol Newsroom",
    sourceKeys: ["europol newsroom", "europol.europa.eu/cms/api/rss/news"],
    include: [
      "administrative documents",
      "border",
      "counterfeit",
      "counterfeiting",
      "currency counterfeiting",
      "document fraud",
      "electronic evidence",
      "fake document",
      "forgery",
      "identity",
      "identity document",
      "migrant smuggling",
      "passport",
      "security",
      "travel document",
    ],
    protectedInclude: [
      "counterfeit",
      "counterfeiting",
      "currency counterfeiting",
      "document fraud",
      "forgery",
      "identity document",
      "migrant smuggling",
    ],
    exclude: [
      "cultural property",
      "drug trafficking",
      "environmental crime",
      "labour exploitation",
      "museum",
      "wildlife",
    ],
  },
  {
    name: "INTERPOL News",
    sourceKeys: ["interpol news", "interpol.int/en/news-and-events/news"],
    rejectExactPaths: [
      "/en/news-and-events/news",
    ],
    include: [
      "border",
      "biometric",
      "counterfeit",
      "counterfeiting",
      "document fraud",
      "fake document",
      "forgery",
      "human trafficking",
      "identity",
      "identity document",
      "illegal migration",
      "irregular migrants",
      "migrant smuggling",
      "passport",
      "security",
      "stolen travel documents",
      "travel document",
    ],
    protectedInclude: [
      "document fraud",
      "fake document",
      "forgery",
      "identity document",
      "irregular migrants",
      "migrant smuggling",
      "stolen travel documents",
      "travel document",
    ],
    exclude: [
      "environmental crime",
      "firearms",
      "gold mining",
    ],
  },
  {
    name: "TSA Press Releases",
    sourceKeys: ["tsa press releases", "tsa.gov/news/press/releases"],
    rejectExactPaths: [
      "/news/press/releases",
    ],
    include: [
      "airport security",
      "biometric",
      "credential",
      "digital identity",
      "facial recognition",
      "identity",
      "identity management",
      "identity theft",
      "identification",
      "passport",
      "precheck",
      "real id",
      "screening",
      "secure flight",
      "security",
      "transportation security",
      "travel document",
    ],
    protectedInclude: [
      "biometric",
      "digital identity",
      "facial recognition",
      "identification",
      "passport",
      "real id",
      "travel document",
    ],
    exclude: [
      "assaulting transportation security officers",
      "drug trafficking",
      "fifa",
      "state fair",
    ],
  },
  {
    name: "NIST Digital Identity News",
    sourceKeys: ["nist digital identity news", "nist.gov/news-events/news/rss.xml"],
    include: [
      "authentication",
      "biometric",
      "biometrics",
      "cybersecurity",
      "digital identity",
      "digital identities",
      "facial recognition",
      "identity",
      "identity proofing",
      "identity verification",
      "mobile driver",
      "mobile driver license",
      "mobile driver's license",
      "mdl",
      "nist sp 800-63",
      "passwordless",
      "privacy",
      "security",
    ],
    protectedInclude: [
      "authentication",
      "biometric",
      "digital identity",
      "digital identities",
      "facial recognition",
      "identity proofing",
      "identity verification",
      "mobile driver",
      "mobile driver license",
      "mobile driver's license",
      "mdl",
      "nist sp 800-63",
    ],
    exclude: [
      "chemistry",
      "climate",
      "manufacturing",
      "quantum",
      "semiconductor",
    ],
  },
  {
    name: "ENISA News",
    sourceKeys: ["enisa news", "enisa.europa.eu/news"],
    rejectExactPaths: [
      "/news",
    ],
    include: [
      "authentication",
      "certification",
      "critical sectors",
      "cyber resilience",
      "cybersecurity",
      "digital identity",
      "eidas",
      "electronic identification",
      "identity",
      "managed security services",
      "nis2",
      "security",
      "trust services",
      "wallet",
    ],
    protectedInclude: [
      "authentication",
      "certification",
      "cyber resilience",
      "digital identity",
      "eidas",
      "electronic identification",
      "managed security services",
      "trust services",
      "wallet",
    ],
    exclude: [
      "challenge for women",
      "competition",
      "skills and competences",
    ],
  },
  {
    name: "OpenID Foundation News",
    sourceKeys: ["openid foundation news", "openid.net/feed"],
    include: [
      "authentication",
      "credential",
      "digital identity",
      "digital wallet",
      "eidas",
      "government identity",
      "identity assurance",
      "identity verification",
      "digital id act",
      "digital trust",
      "openid connect",
      "openid federation",
      "openid for verifiable credential issuance",
      "openid for verifiable presentations",
      "openid4vci",
      "openid4vp",
      "verifiable credential",
      "wallet",
    ],
    protectedInclude: [
      "digital identity",
      "digital wallet",
      "identity assurance",
      "identity verification",
      "digital id act",
      "digital trust",
      "openid connect",
      "openid federation",
      "openid4vci",
      "openid4vp",
      "verifiable credential",
    ],
    exclude: [],
  },
  {
    name: "GovTech Singapore Digital Identity News",
    sourceKeys: ["govtech singapore digital identity news", "tech.gov.sg/media"],
    include: [
      "authentication",
      "digital ic",
      "digital identity",
      "digital signing",
      "face verification",
      "identity verification",
      "myinfo",
      "national digital identity",
      "passkey",
      "passkeys",
      "singpass",
      "verifiable credential",
    ],
  },
  {
    name: "Hong Kong Immigration Department News",
    sourceKeys: ["hong kong immigration department news", "immd.gov.hk/eng/press"],
    include: [
      "automated passenger clearance",
      "e-channel",
      "e-channel service",
      "electronic passport",
      "hong kong identity card",
      "hong kong identity cards",
      "identity card",
      "identity cards",
      "passport",
      "passports",
      "travel document",
      "travel documents",
    ],
    exclude: [
      "anti-illegal worker",
      "arrested during",
      "conspiracy to defraud",
      "illegal worker",
      "illegal workers",
      "jailed",
      "repatriates",
      "repatriation",
      "unsubstantiated non-refoulement",
    ],
  },
  {
    name: "IRCC Passport and Digital Identity News",
    sourceKeys: [
      "ircc passport and digital identity news",
      "departmentofcitizenshipandimmigration",
      "api.io.canada.ca/io-server/gc/news/en/v2",
    ],
    include: [
      "biometric",
      "citizenship certificate",
      "digital identity",
      "digital visa",
      "evisa",
      "identity document",
      "online passport",
      "passeport",
      "passeports",
      "permis de résident permanent",
      "renouvellement de passeport",
      "passport",
      "passports",
      "permanent resident card",
      "secure document",
      "travel document",
      "visa",
    ],
    protectedInclude: [
      "biometric",
      "digital identity",
      "digital visa",
      "evisa",
      "identity document",
      "online passport",
      "passeport",
      "renouvellement de passeport",
      "passport",
      "travel document",
    ],
    exclude: [
      "fuel excise",
      "housing",
      "labour market",
      "settlement services",
    ],
  },
  {
    name: "AAMVA News",
    sourceKeys: ["aamva news", "aamva.org/publications-news/aamva-news"],
    rejectExactPaths: ["/publications-news/aamva-news"],
    include: [
      "digital identity",
      "digital trust service",
      "driver license",
      "driver's license",
      "driving licence",
      "identity card",
      "identity management",
      "iso 18013",
      "mobile driver license",
      "mobile driver's license",
      "mobile driving licence",
      "mdl",
    ],
    protectedInclude: [
      "digital identity",
      "digital trust service",
      "iso 18013",
      "mobile driver license",
      "mobile driver's license",
      "mobile driving licence",
      "mdl",
    ],
    exclude: [
      "commercial vehicle",
      "license plate",
      "motorcycle",
      "podcast",
      "vehicle title",
      "webinar",
    ],
  },
  {
    name: "European Commission Digital Identity News",
    sourceKeys: [
      "european commission digital identity news",
      "digital-strategy.ec.europa.eu/en/policies/electronic-identification",
    ],
    rejectExactPaths: ["/en/policies/electronic-identification"],
    include: [
      "digital identity",
      "digital identity wallet",
      "eidas",
      "electronic identification",
      "european digital identity",
      "identity wallet",
      "large scale pilot",
      "verifiable credential",
      "wallet",
    ],
    protectedInclude: [
      "digital identity",
      "digital identity wallet",
      "eidas",
      "electronic identification",
      "european digital identity",
      "identity wallet",
    ],
    exclude: [],
  },
  {
    name: "Bank of Canada News",
    sourceKeys: ["bank of canada news", "bankofcanada.ca/utility/news/feed"],
    include: [
      "bank note",
      "bank notes",
      "banknote",
      "banknotes",
      "cash",
      "counterfeit",
      "currency",
      "denomination",
      "legal tender",
      "note design",
      "polymer",
    ],
    protectedInclude: [
      "bank note",
      "banknote",
      "counterfeit",
      "denomination",
      "note design",
      "polymer",
    ],
    exclude: [
      "interest rate",
      "monetary policy",
    ],
  },
  {
    name: "Bank of England News",
    sourceKeys: ["bank of england news", "bankofengland.co.uk/rss/news"],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "counterfeit",
      "counterfeit note",
      "counterfeit banknote",
      "denomination",
      "legal tender",
      "note design",
      "polymer",
      "wholesale cash",
      "withdrawn banknotes",
    ],
    protectedInclude: [
      "banknote",
      "counterfeit",
      "counterfeit note",
      "counterfeit banknote",
      "denomination",
      "note design",
      "polymer",
      "withdrawn banknotes",
    ],
    exclude: [
      "interest rate",
      "monetary policy",
      "monetary policy report",
      "financial stability",
    ],
  },
  {
    name: "European Central Bank Press Releases",
    sourceKeys: ["european central bank press releases", "ecb.europa.eu/rss/press.html"],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "cash 2030",
      "counterfeit",
      "counterfeiting",
      "currency",
      "denomination",
      "euro banknote",
      "euro banknotes",
      "legal tender",
      "note design",
      "security feature",
    ],
    protectedInclude: [
      "banknote",
      "counterfeit",
      "counterfeiting",
      "cash",
      "euro banknote",
      "euro cash",
      "legal tender",
      "note design",
      "security feature",
    ],
    protectedIncludeOverridesExclude: true,
    exclude: [
      "interest rate",
      "monetary policy",
      "monetary policy decision",
      "monetary policy account",
      "financial stability",
    ],
  },
  {
    name: "Reserve Bank of Australia Media Releases",
    sourceKeys: [
      "reserve bank of australia media releases",
      "rba.gov.au/rss/rss-cb-media-releases.xml",
    ],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "cash distribution",
      "counterfeit",
      "currency",
      "denomination",
      "note design",
      "polymer",
    ],
    protectedInclude: [
      "banknote",
      "cash distribution",
      "counterfeit",
      "denomination",
      "note design",
      "polymer",
    ],
    exclude: [
      "interest rate",
      "monetary policy",
      "payments system board",
    ],
  },
  {
    name: "South African Reserve Bank News",
    sourceKeys: [
      "south african reserve bank news",
      "resbank.co.za/bin/sarb/solr/publications/rss",
    ],
    include: [
      "banknote",
      "banknotes",
      "cash",
      "cash distribution",
      "currency",
      "rand",
      "coin",
      "coins",
      "counterfeit",
      "legal tender",
      "denomination",
      "note design",
      "security feature",
    ],
    protectedInclude: [
      "banknote",
      "cash",
      "currency",
      "counterfeit",
      "legal tender",
      "denomination",
      "note design",
      "security feature",
    ],
    exclude: [
      "interest rate",
      "monetary policy",
      "prudential authority",
      "insurance",
      "banking sector",
      "foreign exchange reserves",
    ],
  },
  {
    // AlpVision also publishes broad brand-protection material. Keep only the
    // document and security-printing subjects relevant to this intelligence feed.
    name: "AlpVision News",
    sourceKeys: ["alpvision news", "alpvision.com/news"],
    include: [
      "banknote",
      "banknotes",
      "currency",
      "document security",
      "hologram",
      "holograms",
      "identity document",
      "identity documents",
      "passport",
      "passports",
      "secure document",
      "secure documents",
      "security printing",
      "tax stamp",
      "tax stamps",
      "travel document",
      "travel documents",
    ],
    exclude: [
      "cannabis",
      "conference",
      "cosmetics",
      "digital product passport",
      "event",
      "events",
      "food",
      "pharma",
      "pharmaceutical",
      "spirits",
      "tobacco",
      "wine",
    ],
    // The website parser can encounter the social-share target rather than
    // the article URL. A LinkedIn login/share page is never an article.
    rejectLinkPatterns: ["linkedin.com/"],
  },
  {
    name: "DERMALOG News",
    sourceKeys: ["dermalog news", "dermalog.com/news"],
    include: [
      "biometric",
      "biometrics",
      "border control",
      "face recognition",
      "fingerprint",
      "fingerprints",
      "identity",
      "identity document",
      "identity documents",
      "iris recognition",
      "palm scanner",
      "passport",
      "passports",
      "personal identification",
    ],
    exclude: ["award", "awards", "career", "careers", "event", "events", "job", "jobs", "webinar"],
  },
  {
    // Regula's news and blog are relevant where they cover document, biometric
    // or identity verification. The website parser can otherwise encounter a
    // media kit, a product-demo landing page, or the company's LinkedIn block.
    name: "Regula News",
    sourceKeys: ["regula news", "regulaforensics.com/news", "regulaforensics.com/blog/feed"],
    rejectLinkPatterns: ["linkedin.com/", "document-verification-sdk-web-api"],
    include: [
      "age assurance",
      "age verification",
      "ai fraud",
      "biometric",
      "biometrics",
      "credential",
      "credentials",
      "deepfake",
      "digital id",
      "document authentication",
      "document fraud",
      "document processing",
      "document verification",
      "e-passport",
      "epassport",
      "face matching",
      "forensic",
      "identity",
      "identity document",
      "identity fraud",
      "identity verification",
      "id verification",
      "kyc",
      "liveness",
      "passport",
      "passports",
      "banknote",
      "banknotes",
      "travel document",
      "travel documents",
      "watermark",
      "watermarks",
    ],
    exclude: ["media kit", "webinar"],
  },
  {
    // IDEMIA's combined feed contains both Public Security content and the
    // much broader Secure Transactions portfolio. Retain sovereign identity
    // and biometric evidence; exclude payments, cards, and telecom material.
    name: "IDEMIA",
    sourceKeys: ["idemia.com/feed"],
    rejectPagePatterns: ["/video/"],
    include: [
      "age assurance",
      "biometric",
      "biometrics",
      "border security",
      "digital credential",
      "digital identity",
      "document verification",
      "face recognition",
      "identity assurance",
      "identity verification",
      "iris recognition",
      "liveness",
      "mobile driver's license",
      "mobile driver license",
      "passport",
      "passports",
      "traveler processing",
      "travel document",
      "travel documents",
      "verifiable digital credential",
      "verifiable digital credentials",
      "customer id",
    ],
    exclude: [
      "banking card",
      "card issuance",
      "e-sim",
      "esim",
      "google pay",
      "payment card",
      "payment cards",
      "secure transactions",
    ],
  },
  {
    name: "Joh. Enschede",
    sourceKeys: ["joh. enschede", "joh-enschede.nl/feed"],
    include: [
      "banknote",
      "banknotes",
      "currency",
      "note",
      "notes",
      "security printing",
      "security feature",
      "security features",
    ],
    exclude: ["philately", "stamp", "stamps"],
  },
  {
    name: "TOPPAN Security News",
    sourceKeys: ["toppan security news", "toppansecurity.com/news"],
    include: [
      "credential",
      "credentials",
      "digital identity",
      "digital id",
      "identity document",
      "identity documents",
      "id document",
      "id documents",
      "national id",
      "passport",
      "passports",
      "personalization center",
      "personalisation center",
      "secure identity",
      "travel document",
      "travel documents",
    ],
    exclude: ["career", "careers", "event", "events", "job", "jobs", "metal card", "payment card"],
  },
  {
    // secunet's press room also contains financial and broad cybersecurity
    // announcements. Keep only sovereign identity and border-control news.
    name: "secunet Press",
    sourceKeys: ["secunet press", "secunet.com/en/about-us/press"],
    rejectExactPaths: ["/en/about-us/press", "/en/about-us/news-events"],
    rejectPagePatterns: ["/en/industries/"],
    rejectTitlePatterns: ["change in management", "news & events"],
    include: [
      "biometric",
      "biometrics",
      "biometrie",
      "border control",
      "border police",
      "document verification",
      "e-id",
      "eid",
      "einreise-ausreisesystem",
      "einreise ausreisesystem",
      "entry/exit system",
      "entry exit system",
      "grenzkontrolle",
      "grenzpolizei",
      "identity document",
      "identity documents",
      "identitätsdokument",
      "identitätsdokumente",
      "passport",
      "passports",
      "reisepass",
      "reisepässe",
      "reisedokument",
      "reisedokumente",
      "residence permit",
      "residence permits",
      "travel document",
      "travel documents",
      "visa",
      "visas",
    ],
    exclude: [
      "annual report",
      "cloud",
      "cyber resilience",
      "cyberattack",
      "cyberattacks",
      "dividend",
      "earnings",
      "financial",
      "order intake",
      "quarter",
    ],
  },
];

export function getSourceRelevanceRule(feed) {
  const fingerprint = [
    feed?.name,
    feed?.rssUrl,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  return SOURCE_RELEVANCE_RULES.find((rule) =>
    rule.sourceKeys.some((sourceKey) => fingerprint.includes(sourceKey))
  ) || null;
}

function buildSourceTermPattern(term) {
  const normalizedTerm = String(term || "").trim().toLowerCase();
  if (!normalizedTerm) {
    return null;
  }

  const escaped = normalizedTerm
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/\s+/g, "[\\s\\-/&]+");

  return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, "i");
}

export function findSourceRuleMatches(text, terms = []) {
  return terms.filter((term) => {
    const pattern = buildSourceTermPattern(term);
    return pattern ? pattern.test(text) : false;
  });
}

function getArticlePath(article) {
  const rawUrl = String(article?.link || "").trim();
  if (!rawUrl) {
    return "";
  }

  try {
    const parsed = new URL(rawUrl, "https://example.invalid");
    const pathname = parsed.pathname.replace(/\/+$/, "") || "/";
    return pathname.toLowerCase();
  } catch {
    return rawUrl.split("?")[0].replace(/\/+$/, "").toLowerCase();
  }
}

function findRejectedPageMatches(rule, article) {
  const articlePath = getArticlePath(article);
  const title = String(article?.title || "").trim().toLowerCase();
  const link = String(article?.link || "").trim().toLowerCase();
  const rejectedExactPaths = (rule.rejectExactPaths || []).filter((path) =>
    articlePath === String(path || "").replace(/\/+$/, "").toLowerCase()
  );
  const rejectedPathPatterns = (rule.rejectPagePatterns || []).filter((pattern) =>
    articlePath.includes(String(pattern || "").toLowerCase())
  );
  const rejectedTitlePatterns = (rule.rejectTitlePatterns || []).filter((pattern) =>
    title.includes(String(pattern || "").toLowerCase())
  );
  const rejectedLinkPatterns = (rule.rejectLinkPatterns || []).filter((pattern) =>
    link.includes(String(pattern || "").toLowerCase())
  );

  return [
    ...rejectedExactPaths.map((match) => `path:${match}`),
    ...rejectedPathPatterns.map((match) => `path-pattern:${match}`),
    ...rejectedTitlePatterns.map((match) => `title:${match}`),
    ...rejectedLinkPatterns.map((match) => `link-pattern:${match}`),
  ];
}

function articleMatchesProtectedPagePattern(rule, article) {
  const protectedPagePatterns = rule.protectedPagePatterns || [];
  if (!protectedPagePatterns.length) {
    return true;
  }

  const articlePath = getArticlePath(article);
  return protectedPagePatterns.some((pattern) =>
    articlePath.includes(String(pattern || "").toLowerCase())
  );
}

function findGlobalNonArticleLinkMatches(article) {
  const link = String(article?.link || "").trim().toLowerCase();
  return NON_ARTICLE_LINK_PATTERNS.filter((pattern) => link.includes(pattern));
}

export function getSourceRelevanceAssessment(feed, article) {
  const rule = getSourceRelevanceRule(feed);
  const globalNonArticleLinkMatches = findGlobalNonArticleLinkMatches(article);
  if (globalNonArticleLinkMatches.length) {
    return {
      accepted: false,
      rule,
      includedTerms: [],
      excludedTerms: [],
      rejectedPageMatches: globalNonArticleLinkMatches.map((match) => `global-link-pattern:${match}`),
      reason: `rejected-non-article-link:${globalNonArticleLinkMatches.join(", ")}`,
    };
  }
  if (!rule) {
    return {
      accepted: true,
      rule: null,
      includedTerms: [],
      excludedTerms: [],
      reason: "no-source-rule",
    };
  }

  const articleText = [
    article?.title,
    article?.link,
    article?.contentSnippet,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  const publisher = String(article?.source || article?.sourceName || "").toLowerCase();
  const rejectedPageMatches = findRejectedPageMatches(rule, article);
  if (rejectedPageMatches.length) {
    return {
      accepted: false,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms: findSourceRuleMatches(articleText, rule.exclude),
      rejectedPageMatches,
      reason: `rejected-page:${rejectedPageMatches.join(", ")}`,
    };
  }

  const excludedSources = findSourceRuleMatches(publisher, rule.excludeSources || []);
  if (excludedSources.length) {
    return {
      accepted: false,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms: [],
      excludedSources,
      reason: `excluded-publisher:${excludedSources.join(", ")}`,
    };
  }

  const protectedText = [
    article?.title,
    article?.link,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  const protectedTerms = findSourceRuleMatches(protectedText, rule.protectedInclude || []);
  if (
    protectedTerms.length &&
    (rule.protectedIncludeOverridesExclude || articleMatchesProtectedPagePattern(rule, article))
  ) {
    return {
      accepted: true,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms: findSourceRuleMatches(articleText, rule.exclude),
      protectedTerms,
      reason: `protected-source-term:${protectedTerms.join(", ")}`,
    };
  }

  const excludedTerms = findSourceRuleMatches(articleText, rule.exclude);
  if (excludedTerms.length) {
    return {
      accepted: false,
      rule,
      includedTerms: findSourceRuleMatches(articleText, rule.include),
      excludedTerms,
      reason: `excluded-term:${excludedTerms.join(", ")}`,
    };
  }

  const includedTerms = findSourceRuleMatches(articleText, rule.include);
  return {
    accepted: includedTerms.length > 0,
    rule,
    includedTerms,
    excludedTerms: [],
    reason: includedTerms.length > 0 ? "included-term" : "missing-allowlist-term",
  };
}

export function articleMatchesSourceRelevanceRule(feed, article) {
  return getSourceRelevanceAssessment(feed, article).accepted;
}
